# These are supported funding model platforms

github: # Leave blank or add your GitHub Sponsors username if you activate it later
patreon: # Leave blank
open_collective: # Leave blank
ko_fi: quantjourney  # Replace 'quantjourney' with your actual Ko-fi username
tidelift: # Leave blank
community_bridge: # Leave blank
liberapay: # Leave blank
issuehunt: # Leave blank
lfx_crowdfunding: # Leave blank
polar: # Leave blank
buy_me_a_coffee: # Leave blank
thanks_dev: # Leave blank
custom: # Leave blank or add your Substack blog URL if you want (e.g., ['https://quantjourney.substack.com'])
